Repository rust-lang/reference, pull requests merged in 2018-08, with the labels that each got.

#389 Document transparent representation
  src/type-layout.md
Labels: New Content

#376 Expand block expression section
  src/expressions/block-expr.md
Labels: Language Cleanup, New Content

#395 Updated section on identifiers for raw identifiers
  src/identifiers.md
Labels: RFC Stabilization Docs

#388 Stabilize 'attr_literals' feature.
  src/attributes.md
Labels: RFC Stabilization Docs
