Repository rust-lang/reference, pull requests merged in 2018-09, with the labels that each got.

#401 Combine related paragraphs and add more details for implementations
  src/items/implementations.md
Labels: Language Cleanup

#382 Test attributes deserve their own section
  src/attributes.md
  src/crates-and-source-files.md
Labels: New Content

#387 Attributes on functions
  src/attributes.md
  src/expressions/block-expr.md
  src/expressions/match-expr.md
  src/items/functions.md
  src/items/implementations.md
  src/statements.md
Labels: New Content

#400 Stabilize macro_vis_matcher
  src/macros-by-example.md
Labels: RFC Stabilization Docs

#408 Improve Introduction
  src/introduction.md
Labels: Language Cleanup

#424 Add some notes on repetition
  src/macros-by-example.md
Labels: New Content, RFC Stabilization Docs
