Repository rust-lang/reference, pull requests merged in 2020-11, with the labels that each got.

#837 Mention Box's partial field moves
  src/expressions/field-expr.md
Labels: needs-reviewer

#899 Referencify tuples
  src/expressions/tuple-expr.md
  src/patterns.md
  src/types/tuple.md
Labels: A-expressions, A-patterns, A-types

#903 Update where our chat is.
  src/introduction.md
Labels: Bug
