Repository rust-lang/reference, pull requests merged in 2021-02, with the labels that each got.

#953 Define rust
  src/introduction.md
Labels: New Content

#940 Referencify bool type
  src/behavior-considered-undefined.md
  src/expressions/if-expr.md
  src/expressions/loop-expr.md
  src/expressions/operator-expr.md
  src/items/unions.md
  src/types/boolean.md
Labels: A-types, Language Cleanup, New Content, S-waiting-on-review

#874 Add an extra fn() entry to the variance table in the subtyping chapter
  src/subtyping.md
Labels: S-needs-reviewer
