Repository rust-lang/reference, pull requests merged in 2022-05, with the labels that each got.

#1163 Clarify guarantees provided by repr(packed)
  src/type-layout.md
Labels: I-lang-nominated, T-lang

#1214 Remove footnote on warning about lifetime shadowing labels.
  src/names/namespaces.md
Labels: T-lang

#1180 Upper bound on hashes in raw string literals
  src/tokens.md
Labels: I-lang-nominated, T-lang

#1220 Add tile registers to inline-assembly documentation
  src/inline-assembly.md
Labels: A-asm

#1191 Inline assembly: Clarify references to quoted regs
  src/inline-assembly.md
Labels: A-asm
