Repository rust-lang/reference, pull requests merged in 2024-11, with the labels that each got.

#1643 Add s390x to inline-assembly documentation
  src/inline-assembly.md
Labels: S-waiting-on-stabilization

#1638 Add three more WebAssembly features to the list of accepted ones
  src/attributes/codegen.md
Labels: S-waiting-on-stabilization

#1603 Raw lifetimes
  src/identifiers.md
  src/tokens.md
Labels: S-waiting-on-author

#1565 2024: Add updates for unsafe extern blocks
  src/items/external-blocks.md
  src/items/functions.md
  src/unsafe-keyword.md
  src/unsafety.md
Labels: S-waiting-on-stabilization, A-edition-2024

#1592 Add a section dedicated to Edition 2024 changes to temporary scopes
  src/destructors.md
Labels: S-waiting-on-stabilization, A-edition-2024

#1552 Add rust_2024 prelude
  src/names/preludes.md
Labels: S-waiting-on-stabilization, A-edition-2024

#1501 Document `gen` keyword as reserved in Rust 2024
  src/keywords.md
Labels: S-waiting-on-stabilization, A-edition-2024

#1687 Update function-pointer.md for stabilization of `extended_varargs_abi_support`
  src/types/function-pointer.md
Labels: S-waiting-on-stabilization
