Repository rust-lang/reference, pull requests merged in 2024-07, with the labels that each got.

#1502 more explicitly explain the UB around immutable extern statics
  src/behavior-considered-undefined.md
  src/items/external-blocks.md
Labels: T-lang

#1499 elaborate on slice wide pointer metadata
  src/behavior-considered-undefined.md
Labels: T-lang, final-comment-period

#1535 Add review policy for the reference and specification work
  README.md
  docs/review-policy.md
Labels: T-spec

#1541 update 'dangling pointers' to new zero-sized rules
  src/behavior-considered-undefined.md
Labels: A-undefined-behavior, T-opsem
