Repository rust-lang/reference, pull requests merged in 2024-09, with the labels that each got.

#1598 `asm!`: clarify that `nomem` / `readonly` can access private memory
  src/inline-assembly.md
Labels: A-asm

#1590 const_eval: update for const_mut_refs and const_refs_to_cell stabilization
  src/const_eval.md
Labels: S-waiting-on-stabilization

#1596 stabilize `const_extern_fn`
  src/items/functions.md
Labels: S-waiting-on-stabilization

#1563 Add spec identifiers to comments.md
  src/comments.md
Labels: T-spec
