Repository rust-lang/reference, pull requests merged in 2024-12, with the labels that each got.

#1610 `const` expression can borrow static items
  src/const_eval.md
  src/items/constant-items.md
  src/items/static-items.md
Labels: S-waiting-on-review

#1696 Fix paragraphs with trailing `\1`
  src/items/modules.md
  src/types/function-item.md
  src/types/impl-trait.md
  src/types/textual.md
Labels: S-waiting-on-review

#1521 Update closures for edition 2021 disjoint closure capturing
  src/types/closure.md
Labels: S-waiting-on-review, A-edition-2021

#1692 Describe async closures
  mdbook-spec/src/std_links.rs
  src/expressions/await-expr.md
  src/expressions/call-expr.md
  src/expressions/closure-expr.md
  src/items/traits.md
  src/types/closure.md
  src/types/function-pointer.md
Labels: S-waiting-on-stabilization

#1695 Reflect rust#133422 & rust#133587 to inline assembly documentation
  src/inline-assembly.md
Labels: S-waiting-on-review

#1698 Fix rule auto-linking on Windows
  mdbook-spec/src/lib.rs
Labels: S-waiting-on-review

#1697 Clarify that `extern crate foo as føø` is allowed
  src/identifiers.md
Labels: S-waiting-on-review

#1628 `coverage` attribute
  src/SUMMARY.md
  src/attributes.md
  src/attributes/coverage-instrumentation.md
Labels: S-waiting-on-stabilization, S-waiting-on-review

#1663 Add documentation for `#[diagnostic::do_not_recommend]`
  src/attributes.md
  src/attributes/diagnostics.md
Labels: S-waiting-on-stabilization, S-waiting-on-author

#1702 Document Rust 2024 match ergonomics reservations
  src/patterns.md
Labels: S-waiting-on-review

#1706 Revert "`coverage` attribute"
  src/SUMMARY.md
  src/attributes.md
  src/attributes/coverage-instrumentation.md
Labels: S-waiting-on-review
