Repository rust-lang/reference, pull requests merged in 2024-08, with the labels that each got.

#1421 Stabilize Wasm relaxed SIMD
  src/attributes/codegen.md
Labels: S-waiting-on-stabilization, S-blocked

#1536 Changes for unsafe extern blocks (RFC 3484)
  src/items/external-blocks.md
  src/items/functions.md
  src/items/static-items.md
  src/keywords.md
  src/types/never.md
  src/unsafe-keyword.md
  src/unsafety.md
Labels: S-waiting-on-stabilization

#1550 Reformat (and only reformat) the inline assembly chapter
  src/inline-assembly.md
Labels: finished-final-comment-period, T-spec

#1539 Add some basic docs for unsafe attrs
  src/abi.md
  src/attributes.md
  src/unsafe-keyword.md
  src/unsafety.md
Labels: S-waiting-on-stabilization

#1567 operator expressions: add &raw
  src/behavior-considered-undefined.md
  src/expressions.md
  src/expressions/operator-expr.md
  src/items/static-items.md
  src/type-layout.md
  src/types/pointer.md
Labels: S-waiting-on-stabilization

#1571 Add spec identifier syntax to destructors.md
  src/destructors.md
Labels: T-spec

#1566 const_eval: update for const-fn float stabilization
  src/const_eval.md
Labels: S-waiting-on-stabilization
