Repository rust-lang/reference, pull requests merged in 2025-05, with the labels that each got.

#1803 Remove StructExprTuple and StructExprUnit
  src/expressions.md
  src/expressions/if-expr.md
  src/expressions/loop-expr.md
  src/expressions/match-expr.md
  src/expressions/struct-expr.md
Labels: S-waiting-on-review

#1804 Clean up some inline assembly examples
  src/inline-assembly.md
Labels: S-waiting-on-review

#1792 Remove apologies about the Reference
  README.md
  src/introduction.md
Labels: I-lang-nominated, T-lang, finished-final-comment-period, needs-fcp, S-waiting-on-team, to-announce

#1755 Add: orphan rule rationale.
  src/items/implementations.md
Labels: S-waiting-on-review

#1740 Document `let_chains` again
  src/SUMMARY.md
  src/attributes/type_system.md
  src/const_eval.md
  src/destructors.md
  src/expressions.md
  src/expressions/block-expr.md
  src/expressions/if-expr.md
  src/expressions/loop-expr.md
  src/expressions/struct-expr.md
  src/names.md
  src/names/namespaces.md
  src/names/scopes.md
  src/patterns.md
  src/tokens.md
Labels: S-waiting-on-stabilization, S-waiting-on-author

#1812 Add an example admonition
  docs/authoring.md
  mdbook-spec/src/admonitions.rs
  mdbook-spec/src/lib.rs
  src/introduction.md
  theme/reference.css
Labels: S-waiting-on-review

#1810 Fix typo in introduction
  src/introduction.md
Labels: S-waiting-on-review

#1807 Use the reference grammar for inline assembly
  src/inline-assembly.md
Labels: S-waiting-on-review

#1817 Make linked rules are clicked, highlight the color
  theme/reference.css
Labels: S-waiting-on-review

#1820 Fix naked em-dash
  src/attributes.md
Labels: S-waiting-on-review

#1824 Fix grammar for `LiteralPattern` regarding `-`
  src/patterns.md
Labels: S-waiting-on-review

#1825 Fix grammar for `RangePatternBound` regarding literals
  src/patterns.md
Labels: S-waiting-on-review

#1826 Parse optionals and repeats without regexes
  mdbook-spec/src/grammar/parser.rs
  src/items/generics.md
  src/patterns.md
Labels: S-waiting-on-review

#1827 Parse grammar without regexes
  mdbook-spec/src/grammar/parser.rs
Labels: S-waiting-on-review

#1778 Add doc for avx512 target features
  src/attributes/codegen.md
Labels: S-waiting-on-stabilization

#1779 Mention the temporary scope of `while let`.
  src/destructors.md
Labels: S-waiting-on-review

#1788 Enable `[canonicalize-issue-links]` and `[no-mentions]` in triagebot
  triagebot.toml
Labels: S-waiting-on-review

#1822 Explain why nested receivers are dyn-incompatible
  src/items/traits.md
Labels: S-waiting-on-review

#1816 Minor fixes to `$crate` behavior
  src/macros-by-example.md
  src/paths.md
  src/procedural-macros.md
Labels: S-waiting-on-review
