Repository rust-lang/reference, pull requests merged in 2025-01, with the labels that each got.

#1709 Fix unclosed `<sup>` elements
  src/identifiers.md
  src/items.md
  src/items/extern-crates.md
  src/visibility-and-privacy.md
Labels: S-waiting-on-review

#1708 fix typo in a "rule" name in type-coercions.md
  src/type-coercions.md
Labels: S-waiting-on-review

#1582 Add spec identifiers to dynamically-sized-types.md
  src/dynamically-sized-types.md
Labels: S-waiting-on-review, T-spec

#1597 Add Identifier Syntax to Several Chapters
  src/items/constant-items.md
  src/keywords.md
  src/lifetime-elision.md
  src/macros.md
  src/memory-allocation-and-lifetime.md
  src/names.md
  src/paths.md
  src/patterns.md
  src/runtime.md
  src/special-types-and-traits.md
Labels: S-waiting-on-author, T-spec

#1711 Fix filename for theme customization
  docs/authoring.md
Labels: S-waiting-on-review

#1715 references and Box must be non-null
  src/behavior-considered-undefined.md
Labels: S-waiting-on-review

#1718 Move the function pointer example
  src/types/function-pointer.md
Labels: S-waiting-on-review

#1716 Provide a better error message for broken links in mdbook-spec
  mdbook-spec/src/lib.rs
  mdbook-spec/src/std_links.rs
Labels: S-waiting-on-review

#1719 reword reference about inert attributes
  src/attributes.md
Labels: S-waiting-on-review

#1721 Change `'_static` to `'static` as an invalid lifetime parameter name
  src/items/generics.md
Labels: S-waiting-on-review

#1657 distinct 'static' items never overlap
  src/items/static-items.md
Labels: T-lang, T-opsem, finished-final-comment-period

#1648 Spec inline assembly tests
  src/inline-assembly.md
Labels: S-waiting-on-review

#1723 Exclude the test summary from the search index
  book.toml
Labels: S-waiting-on-review

#1591 Add Spec Identifier Syntax to expressions.md and subchapters
  src/expressions.md
  src/expressions/array-expr.md
  src/expressions/await-expr.md
  src/expressions/block-expr.md
  src/expressions/call-expr.md
  src/expressions/closure-expr.md
  src/expressions/field-expr.md
  src/expressions/grouped-expr.md
  src/expressions/if-expr.md
  src/expressions/literal-expr.md
  src/expressions/loop-expr.md
  src/expressions/match-expr.md
  src/expressions/method-call-expr.md
  src/expressions/operator-expr.md
  src/expressions/path-expr.md
  src/expressions/range-expr.md
  src/expressions/return-expr.md
  src/expressions/struct-expr.md
  src/expressions/tuple-expr.md
  src/expressions/underscore-expr.md
Labels: S-waiting-on-review, T-spec
