Repository rust-lang/reference, pull requests merged in 2025-04, with the labels that each got.

#1777 Fix CSS for new footnote style
  .github/workflows/main.yml
  theme/reference.css
Labels: S-waiting-on-review

#1773 Update tools to Rust 2024
  mdbook-spec/Cargo.toml
  mdbook-spec/src/lib.rs
  mdbook-spec/src/rules.rs
  mdbook-spec/src/std_links.rs
  rustfmt.toml
  style-check/Cargo.toml
Labels: S-waiting-on-review

#1774 Add test wrappers
  .cargo/config.toml
  .github/workflows/main.yml
  docs/authoring.md
  xtask/.gitignore
  xtask/Cargo.lock
  xtask/Cargo.toml
  xtask/src/main.rs
Labels: S-waiting-on-review

#1770 Fix header rules
  src/attributes/codegen.md
  src/attributes/debugger.md
  src/attributes/diagnostics.md
  src/attributes/limits.md
  src/attributes/testing.md
  src/behavior-considered-undefined.md
  src/comments.md
  src/conditional-compilation.md
  src/const_eval.md
  src/destructors.md
  src/dynamically-sized-types.md
  src/identifiers.md
  src/inline-assembly.md
  src/input-format.md
  src/linkage.md
  src/macro-ambiguity.md
  src/macros-by-example.md
  src/names/preludes.md
  src/procedural-macros.md
  src/statements-and-expressions.md
  src/statements.md
  src/tokens.md
  src/trait-bounds.md
  src/type-layout.md
  src/types/closure.md
  src/types/numeric.md
  src/unsafe-keyword.md
Labels: S-waiting-on-review

#1771 Rework trait parameter patterns
  src/items/traits.md
Labels: S-waiting-on-review

#1775 Add the ability for rules to be specified in link definitions
  mdbook-spec/src/lib.rs
  src/introduction.md
Labels: S-waiting-on-review

#1776 Update precedence table for borrow operators
  src/expressions.md
Labels: S-waiting-on-review

#1780 Update book.toml fix the authors field
  book.toml
Labels: S-waiting-on-review

#1783 spelling fix, Discrimants -> Discriminants
  src/items/enumerations.md
Labels: S-waiting-on-review

#1782 doc: add missing space
  src/subtyping.md
Labels: S-waiting-on-review

#1784 traits.md: remove unusual formatting
  src/items/traits.md
Labels: S-waiting-on-review

#1786 Fix std::ops links in range-expr
  src/expressions/range-expr.md
Labels: S-waiting-on-review

#1785 Misc. spelling fixes
  src/expressions/block-expr.md
  src/expressions/operator-expr.md
  src/type-layout.md
Labels: S-waiting-on-review

#1793 Add rule identifiers for the ABI chapter
  src/abi.md
Labels: S-waiting-on-review

#1795 Simplify GenericParams grammar
  src/items/generics.md
Labels: S-waiting-on-review

#1791 attributes/codegen: update aarch64 features
  src/attributes/codegen.md
Labels: S-waiting-on-author

#1796 Refactor rendering with `RenderCtx`
  mdbook-spec/src/grammar.rs
  mdbook-spec/src/grammar/render_markdown.rs
  mdbook-spec/src/grammar/render_railroad.rs
Labels: S-waiting-on-review

#1762 Add `cfg(true)` and `cfg(false)` to conditional compilation (RFC 3695)
  src/conditional-compilation.md
Labels: S-waiting-on-author

#1763 Use `cfg(false)` instead of `cfg(FALSE)`
  src/items/enumerations.md
  src/tokens.md
Labels: S-waiting-on-stabilization

#1798 Relabel grammarRailroad-Button
  src/notation.md
  theme/reference.css
  theme/reference.js
Labels: S-waiting-on-review

#1790 Clarify interaction of asm-goto with IBT
  src/inline-assembly.md
Labels: T-lang, finished-final-comment-period

#1799 Improve documentation of struct expressions
  src/expressions/struct-expr.md
Labels: S-waiting-on-review
