Repository rust-lang/reference, pull requests merged in 2025-02, with the labels that each got.

#1713 doc `cenum_impl_drop_cast`
  src/expressions/operator-expr.md
Labels: S-waiting-on-stabilization

#1730 fixup `»` insertion for rules
  theme/reference.css
Labels: S-waiting-on-review

#1732 `as` cast improvements
  src/expressions/operator-expr.md
Labels: S-waiting-on-review

#1733 Rework error handling in mdbook-spec
  mdbook-spec/src/lib.rs
  mdbook-spec/src/rules.rs
  mdbook-spec/src/std_links.rs
Labels: S-waiting-on-review

#1734 Revert "Update function-pointer.md for stabilization of `extended_varargs_abi_support`"
  src/types/function-pointer.md
Labels: S-waiting-on-review, T-spec, S-waiting-on-team

#1736 Remove attributes from struct field rest patterns
  src/patterns.md
Labels: S-waiting-on-review

#1737 Add rule identifiers to names chapters
  src/names/namespaces.md
  src/names/preludes.md
  src/names/scopes.md
Labels: S-waiting-on-review

#1744 Update boolean.md, Comment breaks paragraph format
  src/types/boolean.md
Labels: S-waiting-on-review

#1743 Closures: fix example of desugaring
  src/types/closure.md
Labels: S-waiting-on-review

#1226 panic runtime and C-unwind documentation
  src/SUMMARY.md
  src/attributes.md
  src/attributes/codegen.md
  src/behavior-considered-undefined.md
  src/conditional-compilation.md
  src/crates-and-source-files.md
  src/destructors.md
  src/expressions/array-expr.md
  src/items/external-blocks.md
  src/items/functions.md
  src/linkage.md
  src/panic.md
  src/runtime.md
  src/types/function-pointer.md
Labels: S-waiting-on-author
